[package]
name = "apvm"
version = "0.1.0"
edition = "2024"

[profile.release]
opt-level = 3
debug = false
lto = true
strip = "debuginfo"
panic = 'unwind'
incremental = false
codegen-units = 1
rpath = false

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.36", features = ["derive", "env"] }
flate2 = "1.1.1"
reqwest = "0.12.15"
tar = "0.4.44"
tokio = { version = "1.44.2", features = ["full"] }
urlencoding = "2.1.3"
which = "7.0.3"
xz = "0.1.0"
